FIRST_NAME_LAST_NAME_MAX_LENGTH = 30
GROUP_TITLE_MAX_LENGTH = 150
GROUP_DESCRIPTION_MAX_LENGTH = 1000
JIRA_TOKEN_MAX_LENGTH = 100

INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
EMAIL_CANNOT_UPDATE = 'email cannot be updated'
ADMIN_CANNOT_UPDATE = 'admin cannot be changed'
USER_REMOVED_FROM_GROUP = 'user removed successfully!'
USER_SUCCESSFULLY_LOGOUT = 'User log out successfully'
