# Generated by Django 2.2 on 2021-12-13 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('token_key', models.CharField(max_length=40, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2021, 12, 13, 11, 44, 9, 101193))),
                ('purpose', models.PositiveSmallIntegerField(choices=[(0, 'Signup'), (1, 'Group'), (2, 'Pokerboard')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
