# Generated by Django 2.2 on 2021-12-14 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 9, 53, 43, 228455, tzinfo=utc)),
        ),
    ]
