# Generated by Django 2.2 on 2021-12-22 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20211214_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 11, 8, 54, 299894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='token_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
