# Generated by Django 2.2 on 2021-12-28 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_auto_20211222_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 8, 31, 13, 401644, tzinfo=utc)),
        ),
    ]
