# Generated by Django 2.2 on 2021-12-28 08:01

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0004_auto_20211228_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokerboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('estimate_type', models.PositiveSmallIntegerField(choices=[(0, 'Fibonacci'), (1, 'Odd'), (2, 'Even'), (3, 'Serial'), (4, 'Custom')], default=0)),
                ('deck', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=17, validators=[django.core.validators.MaxValueValidator(100000000000000.0), django.core.validators.MinValueValidator(0.001)]), size=None)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=1200))),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.PositiveIntegerField(unique=True)),
                ('order', models.PositiveIntegerField()),
                ('final_estimate', models.DecimalField(decimal_places=3, max_digits=17, null=True, validators=[django.core.validators.MaxValueValidator(100000000000000.0), django.core.validators.MinValueValidator(0.001)])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'ToDo'), (1, 'InProgress'), (2, 'Completed')], default=0)),
                ('pokerboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerboards.Pokerboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokerboardInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Declined'), (3, 'Cancelled')], default=0)),
                ('role', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Player'), (1, 'Spectator')], default=0), size=None)),
                ('pokerboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerboards.Pokerboard')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.EmailVerification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPokerboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Player'), (1, 'Spectator')], default=0), size=None)),
                ('pokerboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerboards.Pokerboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pokerboard')},
            },
        ),
        migrations.CreateModel(
            name='PlayerTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.DecimalField(decimal_places=3, max_digits=17, null=True, validators=[django.core.validators.MaxValueValidator(100000000000000.0), django.core.validators.MinValueValidator(0.001)])),
                ('time_taken', models.DurationField(default=datetime.timedelta(seconds=1200))),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerboards.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ticket')},
            },
        ),
    ]
