FIBONACCI = 0
ODD = 1
EVEN = 2
SERIAL = 3
CUSTOM = 4

PLAYER = 0
SPECTATOR = 1

TODO = 0
INPROGRESS = 1
COMPLETED = 2

POKERBOARD_NAME_MAX_LENGTH = 50
ESTIMATE_MAX_DIGITS = 17
ESTIMATE_DECIMAL_PLACES = 3
ESTIMATE_MAX_VALUE = 1e+14
ESTIMATE_MIN_VALUE = 0.001
TIMER_DEFAULT_MINUTES = 20
